name: Deploy Flask App (Docker)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # or ubuntu-latest if Docker is available
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t flask-app:latest .

      - name: Run Docker container
        run: docker run -d -p 5000:5000 flask-app:latest
