name: Flask CI/CD

on:
  push:
    branches: ["main"]

jobs:
  # -------------------
  # Stage 1: Build
  # -------------------
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

  # -------------------
  # Stage 2: Test
  # -------------------
  test:
    name: Test Stage
    runs-on: ubuntu-latest
    needs: build   # wait for build stage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest

  # -------------------
  # Stage 3: Docker Build & Push
  # -------------------
  docker:
    name: Docker Stage
    runs-on: ubuntu-latest
    needs: test   # wait for test stage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: abdraheem98/my-flask-app:latest

  # -------------------
  # Stage 4: Deploy
  # -------------------
  deploy:
    name: Deploy Stage
    runs-on: ubuntu-latest
    needs: docker   # wait for docker stage
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull abdraheem98/my-flask-app:latest
            docker stop flask-app || true
            docker rm flask-app || true
            docker run -d -p 80:5000 --name flask-app abdraheem98/my-flask-app:latest
