name: urlapp
on:
  push:
    branches: ["main"]
jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: pip install -r requirements.txt
  test:
    name: test Stage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: pip install pytest
      - name: Run pytest
        run: pytest tests/
