name: urlapp
on:
  push:
    branches: ["main"]
jobs:
  build:
    name: Build Stage
    runs_on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: pip install -r requirements.txt
